### ISSUE TITLE
Black screen when using SDDM as display manager

### ISSUE THREAD

**Issue by E-Berry** [paltas/SUSEPrime#2]
Hello

Using Tumbleweed KDE, suse-prime-alt.
Tested with Nvidia drivers 364.15 and 361.42 from the bumblebee project

When using the nvidia card, if SDDM is set as the display manager, the screen will be black, both after login out and rebooting. To work around this, I used xdm as display manager to log in. 

Aside from this, everything else works.

**Comment by ghost** [comment]
Hm that's wierd, SDDM used to work perfectly with nvidia. I sold my optimus laptop, so I am not really able to help anymore. Sorry.
